# PART - 1

regtest=1
server=1
rest=1
rpcuser=harshith
rpcpassword=iitindore



paytxfee=0.0001
fallbackfee=0.0002
mintxfee=0.00001
txconfirmtarget=6

#PART - 2

RPC_USER="varshith"
RPC_PASSWORD="varshith@CS216"
RPC_HOST="127.0.0.1"
RPC_PORT=18443
